-- =====================================================
-- SKRAWL GAME - SAMPLE WORDS DATA (300+ WORDS)
-- =====================================================

INSERT INTO words (word, difficulty, category) VALUES
-- Easy words - Animals
('cat', 'easy', 'animals'),
('dog', 'easy', 'animals'),
('fish', 'easy', 'animals'),
('bird', 'easy', 'animals'),
('cow', 'easy', 'animals'),
('pig', 'easy', 'animals'),
('duck', 'easy', 'animals'),
('frog', 'easy', 'animals'),
('bee', 'easy', 'animals'),
('ant', 'easy', 'animals'),
('bear', 'easy', 'animals'),
('lion', 'easy', 'animals'),
('tiger', 'easy', 'animals'),
('mouse', 'easy', 'animals'),
('rabbit', 'easy', 'animals'),
('horse', 'easy', 'animals'),
('sheep', 'easy', 'animals'),
('goat', 'easy', 'animals'),
('chicken', 'easy', 'animals'),
('snake', 'easy', 'animals'),

-- Easy words - Vehicles
('car', 'easy', 'vehicles'),
('bus', 'easy', 'vehicles'),
('bike', 'easy', 'vehicles'),
('boat', 'easy', 'vehicles'),
('plane', 'easy', 'vehicles'),
('train', 'easy', 'vehicles'),
('truck', 'easy', 'vehicles'),
('taxi', 'easy', 'vehicles'),
('ship', 'easy', 'vehicles'),
('rocket', 'easy', 'vehicles'),

-- Easy words - Objects
('house', 'easy', 'objects'),
('book', 'easy', 'objects'),
('chair', 'easy', 'objects'),
('table', 'easy', 'objects'),
('ball', 'easy', 'objects'),
('cup', 'easy', 'objects'),
('hat', 'easy', 'objects'),
('shoe', 'easy', 'objects'),
('key', 'easy', 'objects'),
('door', 'easy', 'objects'),
('window', 'easy', 'objects'),
('clock', 'easy', 'objects'),
('lamp', 'easy', 'objects'),
('pen', 'easy', 'objects'),
('box', 'easy', 'objects'),
('bag', 'easy', 'objects'),
('phone', 'easy', 'objects'),
('spoon', 'easy', 'objects'),
('fork', 'easy', 'objects'),
('knife', 'easy', 'objects'),

-- Easy words - Nature
('tree', 'easy', 'nature'),
('sun', 'easy', 'nature'),
('moon', 'easy', 'nature'),
('flower', 'easy', 'nature'),
('grass', 'easy', 'nature'),
('cloud', 'easy', 'nature'),
('star', 'easy', 'nature'),
('rock', 'easy', 'nature'),
('water', 'easy', 'nature'),
('fire', 'easy', 'nature'),
('leaf', 'easy', 'nature'),
('snow', 'easy', 'nature'),
('rain', 'easy', 'nature'),
('wind', 'easy', 'nature'),
('beach', 'easy', 'nature'),

-- Easy words - Food
('apple', 'easy', 'food'),
('pizza', 'easy', 'food'),
('cake', 'easy', 'food'),
('ice cream', 'easy', 'food'),
('banana', 'easy', 'food'),
('cookie', 'easy', 'food'),
('bread', 'easy', 'food'),
('milk', 'easy', 'food'),
('egg', 'easy', 'food'),
('cheese', 'easy', 'food'),
('orange', 'easy', 'food'),
('grape', 'easy', 'food'),
('carrot', 'easy', 'food'),
('potato', 'easy', 'food'),
('tomato', 'easy', 'food'),
('corn', 'easy', 'food'),
('rice', 'easy', 'food'),
('soup', 'easy', 'food'),
('candy', 'easy', 'food'),
('donut', 'easy', 'food'),

-- Easy words - Body Parts
('eye', 'easy', 'body'),
('nose', 'easy', 'body'),
('mouth', 'easy', 'body'),
('ear', 'easy', 'body'),
('hand', 'easy', 'body'),
('foot', 'easy', 'body'),
('head', 'easy', 'body'),
('arm', 'easy', 'body'),
('leg', 'easy', 'body'),
('hair', 'easy', 'body'),

-- Easy words - Actions
('run', 'easy', 'actions'),
('jump', 'easy', 'actions'),
('walk', 'easy', 'actions'),
('swim', 'easy', 'actions'),
('fly', 'easy', 'actions'),
('eat', 'easy', 'actions'),
('sleep', 'easy', 'actions'),
('dance', 'easy', 'actions'),
('sing', 'easy', 'actions'),
('laugh', 'easy', 'actions'),

-- Easy words - Colors
('red', 'easy', 'colors'),
('blue', 'easy', 'colors'),
('green', 'easy', 'colors'),
('yellow', 'easy', 'colors'),
('black', 'easy', 'colors'),
('white', 'easy', 'colors'),
('pink', 'easy', 'colors'),
('purple', 'easy', 'colors'),
('orange', 'easy', 'colors'),
('brown', 'easy', 'colors'),

-- Medium words - Animals
('elephant', 'medium', 'animals'),
('butterfly', 'medium', 'animals'),
('giraffe', 'medium', 'animals'),
('penguin', 'medium', 'animals'),
('kangaroo', 'medium', 'animals'),
('dolphin', 'medium', 'animals'),
('octopus', 'medium', 'animals'),
('crocodile', 'medium', 'animals'),
('zebra', 'medium', 'animals'),
('monkey', 'medium', 'animals'),
('turtle', 'medium', 'animals'),
('whale', 'medium', 'animals'),
('shark', 'medium', 'animals'),
('eagle', 'medium', 'animals'),
('owl', 'medium', 'animals'),
('peacock', 'medium', 'animals'),
('flamingo', 'medium', 'animals'),
('parrot', 'medium', 'animals'),
('squirrel', 'medium', 'animals'),
('hedgehog', 'medium', 'animals'),

-- Medium words - Vehicles
('helicopter', 'medium', 'vehicles'),
('motorcycle', 'medium', 'vehicles'),
('submarine', 'medium', 'vehicles'),
('ambulance', 'medium', 'vehicles'),
('fire truck', 'medium', 'vehicles'),
('bulldozer', 'medium', 'vehicles'),
('tractor', 'medium', 'vehicles'),
('scooter', 'medium', 'vehicles'),
('sailboat', 'medium', 'vehicles'),
('spaceship', 'medium', 'vehicles'),

-- Medium words - Objects
('computer', 'medium', 'objects'),
('telephone', 'medium', 'objects'),
('guitar', 'medium', 'objects'),
('piano', 'medium', 'objects'),
('camera', 'medium', 'objects'),
('television', 'medium', 'objects'),
('refrigerator', 'medium', 'objects'),
('microwave', 'medium', 'objects'),
('toothbrush', 'medium', 'objects'),
('umbrella', 'medium', 'objects'),
('backpack', 'medium', 'objects'),
('suitcase', 'medium', 'objects'),
('bicycle', 'medium', 'objects'),
('ladder', 'medium', 'objects'),
('hammer', 'medium', 'objects'),
('screwdriver', 'medium', 'objects'),
('paintbrush', 'medium', 'objects'),
('scissors', 'medium', 'objects'),
('calculator', 'medium', 'objects'),
('flashlight', 'medium', 'objects'),

-- Medium words - Nature
('rainbow', 'medium', 'nature'),
('mountain', 'medium', 'nature'),
('ocean', 'medium', 'nature'),
('volcano', 'medium', 'nature'),
('desert', 'medium', 'nature'),
('forest', 'medium', 'nature'),
('waterfall', 'medium', 'nature'),
('lightning', 'medium', 'nature'),
('tornado', 'medium', 'nature'),
('earthquake', 'medium', 'nature'),
('glacier', 'medium', 'nature'),
('canyon', 'medium', 'nature'),
('island', 'medium', 'nature'),
('valley', 'medium', 'nature'),
('river', 'medium', 'nature'),

-- Medium words - Food
('sandwich', 'medium', 'food'),
('hamburger', 'medium', 'food'),
('spaghetti', 'medium', 'food'),
('pancake', 'medium', 'food'),
('waffle', 'medium', 'food'),
('burrito', 'medium', 'food'),
('taco', 'medium', 'food'),
('salad', 'medium', 'food'),
('yogurt', 'medium', 'food'),
('cereal', 'medium', 'food'),
('muffin', 'medium', 'food'),
('pretzel', 'medium', 'food'),
('popcorn', 'medium', 'food'),
('chocolate', 'medium', 'food'),
('strawberry', 'medium', 'food'),
('watermelon', 'medium', 'food'),
('pineapple', 'medium', 'food'),
('avocado', 'medium', 'food'),
('broccoli', 'medium', 'food'),
('mushroom', 'medium', 'food'),

-- Medium words - Places
('school', 'medium', 'places'),
('hospital', 'medium', 'places'),
('library', 'medium', 'places'),
('restaurant', 'medium', 'places'),
('supermarket', 'medium', 'places'),
('playground', 'medium', 'places'),
('museum', 'medium', 'places'),
('theater', 'medium', 'places'),
('stadium', 'medium', 'places'),
('airport', 'medium', 'places'),
('hotel', 'medium', 'places'),
('bank', 'medium', 'places'),
('post office', 'medium', 'places'),
('gas station', 'medium', 'places'),
('pharmacy', 'medium', 'places'),

-- Medium words - Events
('birthday', 'medium', 'events'),
('vacation', 'medium', 'events'),
('wedding', 'medium', 'events'),
('party', 'medium', 'events'),
('concert', 'medium', 'events'),
('festival', 'medium', 'events'),
('picnic', 'medium', 'events'),
('camping', 'medium', 'events'),
('meeting', 'medium', 'events'),
('interview', 'medium', 'events'),

-- Medium words - Sports
('football', 'medium', 'sports'),
('basketball', 'medium', 'sports'),
('baseball', 'medium', 'sports'),
('tennis', 'medium', 'sports'),
('soccer', 'medium', 'sports'),
('swimming', 'medium', 'sports'),
('running', 'medium', 'sports'),
('cycling', 'medium', 'sports'),
('skiing', 'medium', 'sports'),
('surfing', 'medium', 'sports'),

-- Hard words - Science
('microscope', 'hard', 'science'),
('telescope', 'hard', 'science'),
('photosynthesis', 'hard', 'science'),
('gravity', 'hard', 'science'),
('constellation', 'hard', 'science'),
('metamorphosis', 'hard', 'science'),
('archaeology', 'hard', 'science'),
('biology', 'hard', 'science'),
('chemistry', 'hard', 'science'),
('physics', 'hard', 'science'),
('astronomy', 'hard', 'science'),
('geology', 'hard', 'science'),
('ecosystem', 'hard', 'science'),
('evolution', 'hard', 'science'),
('molecule', 'hard', 'science'),
('chromosome', 'hard', 'science'),
('mitochondria', 'hard', 'science'),
('photosynthesis', 'hard', 'science'),
('electromagnetic', 'hard', 'science'),
('thermodynamics', 'hard', 'science'),

-- Hard words - Concepts
('architecture', 'hard', 'concepts'),
('democracy', 'hard', 'concepts'),
('philosophy', 'hard', 'concepts'),
('imagination', 'hard', 'concepts'),
('creativity', 'hard', 'concepts'),
('adventure', 'hard', 'concepts'),
('friendship', 'hard', 'concepts'),
('responsibility', 'hard', 'concepts'),
('independence', 'hard', 'concepts'),
('perseverance', 'hard', 'concepts'),
('determination', 'hard', 'concepts'),
('compassion', 'hard', 'concepts'),
('integrity', 'hard', 'concepts'),
('wisdom', 'hard', 'concepts'),
('courage', 'hard', 'concepts'),
('justice', 'hard', 'concepts'),
('equality', 'hard', 'concepts'),
('freedom', 'hard', 'concepts'),
('harmony', 'hard', 'concepts'),
('serenity', 'hard', 'concepts'),

-- Hard words - Technology
('artificial intelligence', 'hard', 'technology'),
('cryptocurrency', 'hard', 'technology'),
('nanotechnology', 'hard', 'technology'),
('biotechnology', 'hard', 'technology'),
('virtual reality', 'hard', 'technology'),
('quantum computing', 'hard', 'technology'),
('robotics', 'hard', 'technology'),
('cybersecurity', 'hard', 'technology'),
('blockchain', 'hard', 'technology'),
('automation', 'hard', 'technology'),

-- Hard words - Medicine
('stethoscope', 'hard', 'medicine'),
('antibiotics', 'hard', 'medicine'),
('vaccination', 'hard', 'medicine'),
('anesthesia', 'hard', 'medicine'),
('diagnosis', 'hard', 'medicine'),
('surgery', 'hard', 'medicine'),
('rehabilitation', 'hard', 'medicine'),
('prescription', 'hard', 'medicine'),
('emergency', 'hard', 'medicine'),
('treatment', 'hard', 'medicine'),

-- Hard words - Geography
('continent', 'hard', 'geography'),
('hemisphere', 'hard', 'geography'),
('equator', 'hard', 'geography'),
('latitude', 'hard', 'geography'),
('longitude', 'hard', 'geography'),
('archipelago', 'hard', 'geography'),
('peninsula', 'hard', 'geography'),
('plateau', 'hard', 'geography'),
('tundra', 'hard', 'geography'),
('savanna', 'hard', 'geography'),

-- Hard words - Events
('celebration', 'hard', 'events'),
('graduation', 'hard', 'events'),
('expedition', 'hard', 'events'),
('conference', 'hard', 'events'),
('symposium', 'hard', 'events'),
('inauguration', 'hard', 'events'),
('ceremony', 'hard', 'events'),
('anniversary', 'hard', 'events'),
('commemoration', 'hard', 'events'),
('demonstration', 'hard', 'events'),

-- Hard words - Places
('laboratory', 'hard', 'places'),
('observatory', 'hard', 'places'),
('auditorium', 'hard', 'places'),
('planetarium', 'hard', 'places'),
('aquarium', 'hard', 'places'),
('conservatory', 'hard', 'places'),
('monastery', 'hard', 'places'),
('cathedral', 'hard', 'places'),
('embassy', 'hard', 'places'),
('parliament', 'hard', 'places'),

-- Hard words - Professions
('archaeologist', 'hard', 'professions'),
('veterinarian', 'hard', 'professions'),
('entrepreneur', 'hard', 'professions'),
('psychiatrist', 'hard', 'professions'),
('anthropologist', 'hard', 'professions'),
('meteorologist', 'hard', 'professions'),
('cardiologist', 'hard', 'professions'),
('neurologist', 'hard', 'professions'),
('dermatologist', 'hard', 'professions'),
('ophthalmologist', 'hard', 'professions'),

-- Hard words - Arts
('masterpiece', 'hard', 'arts'),
('sculpture', 'hard', 'arts'),
('symphony', 'hard', 'arts'),
('choreography', 'hard', 'arts'),
('calligraphy', 'hard', 'arts'),
('renaissance', 'hard', 'arts'),
('impressionism', 'hard', 'arts'),
('abstract', 'hard', 'arts'),
('contemporary', 'hard', 'arts'),
('exhibition', 'hard', 'arts')
ON CONFLICT (word) DO NOTHING;
